name: payment_launcher
description: "Flutter payment launcher plugin for Uzbekistan."
version: 1.0.0
homepage: https://github.com/sherzodkamoldinov/payment_launcher

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.sherzodkamoldinov.payment_launcher
        pluginClass: PaymentLauncherPlugin
      ios:
        pluginClass: PaymentLauncherPlugin

  assets:
    - assets/icons/
